### PR TITLE
Include android aars in meta

### PR DESCRIPTION
**Pull request by Bucimis**

### CODE REVIEW

**Comment by kolibrigames-ajimine-vahid** [comment]
Yup, looks good. I'm guessing this would be a 2.6.1 release 😄

**Comment by kolibrigames-ajimine-vahid** [comment]
It also added in additional platforms for when I changed it, but I think it shouldn't affect others as much
image

**Comment by Bucimis** [comment]
@kolibrigames-ajimine-vahid thanks, just pushed an update - can you take a look?

**Comment by kolibrigames-ajimine-vahid** [comment]
Yup, looks like this change also works

**Comment by Bucimis** [comment]
@kolibrigames-ajimine-vahid heads up that we're going to merge this into our private repo and push the changes to this repo in the next release. Our release artifacts for 2.6.0 have been patched with the fix https://github.com/Appboy/appboy-unity-sdk/releases/tag/2.6.0

**Pull request closed without merging**
